Repository validatorjs/validator.js, pull requests merged in 2019-05, with the labels that each got.

#1004 feat: isEmail: validate display name using standards of RFC2822
  src/lib/isEmail.js
  test/validators.js
Labels: needs-more-review, ready-to-land

#1007 Feature/check email max length
  README.md
  lib/isEmail.js
  src/lib/isEmail.js
  test/validators.js
Labels: discussion

#1022 fix(isMobilePhone): update zh-CN validation
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land

#1023 Add isBase32 validator
  README.md
  index.js
  lib/isBase32.js
  src/index.js
  src/lib/isBase32.js
  test/validators.js
  validator.js
  validator.min.js
Labels: to-be-reviewed

#1035 isMobilePhone: add Chile locale and additional prefix for KE locale
  lib/isMobilePhone.js
  src/lib/isMobilePhone.js
  test/validators.js
  validator.js
  validator.min.js
Labels: ready-to-land
