Repository validatorjs/validator.js, pull requests merged in 2020-09, with the labels that each got.

#1419 fix isBase64 and isBase32 seeing empty string as invalid, fixes #1418
  src/lib/isBase32.js
  src/lib/isBase64.js
  test/validators.js
Labels: needs-more-review

#1436 add(isURL): added require_port option
  README.md
  src/lib/isURL.js
  test/validators.js
Labels: needs-more-review

#1435 Do not validate the length of email parts if ignore_max_length is true
  src/lib/isEmail.js
  test/validators.js
Labels: needs-more-review, 🍿 discussion

#1402 refactor(isDate): add strictMode and prevent mixed delimiters
  README.md
  src/lib/isDate.js
  test/validators.js
Labels: 🕑 to-be-reviewed

#1409 Refactor isTaxID for supporting more locales
  src/lib/isTaxID.js
Labels: needs-more-review
