Repository validatorjs/validator.js, pull requests merged in 2020-04, with the labels that each got.

#1112 added support for Tunisia National Identity Card
  README.md
  package.json
  src/lib/isIdentityCard.js
  test/validators.js
Labels: mc-to-land

#1270 feat: add new isDate() validator
  README.md
  es/index.js
  es/lib/isDate.js
  index.js
  lib/isDate.js
  src/index.js
  src/lib/isDate.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-more-review

#1281 add support for zh-CN in isIdentityCard()
  README.md
  es/lib/isIdentityCard.js
  lib/isIdentityCard.js
  src/lib/isIdentityCard.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-tests
