Repository validatorjs/validator.js, pull requests merged in 2020-02, with the labels that each got.

#1163 add isBtcAddress validator
  README.md
  index.js
  lib/isBtcAddress.js
  src/index.js
  src/lib/isBtcAddress.js
  test/validators.js
  validator.js
  validator.min.js
Labels: ready-to-land, 🧹 needs-update

#1244 feat(isEAN): implement isEAN validator
  README.md
  index.js
  lib/isEAN.js
  src/index.js
  src/lib/isEAN.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-more-review

#1131 Add coverage report
  .travis.yml
  README.md
Labels: 🧹 needs-update

#1211 Bugfix - Wrong IP address validation
  es/lib/isIP.js
  lib/isIP.js
  src/lib/isIP.js
  test/validators.js
Labels: 🧹 needs-update

#1141 Add isRgbColor validator
  README.md
  index.js
  lib/isRgbColor.js
  src/index.js
  src/lib/isRgbColor.js
  test/validators.js
  validator.js
  validator.min.js
Labels: ready-to-land, 🧹 needs-update

#1072 feat(isLocale): validate isLocale
  README.md
  src/index.js
  src/lib/isLocale.js
  test/validators.js
Labels: ready-to-land, 🧹 needs-update

#1117 Add isEthereumAddress
  README.md
  index.js
  lib/isEthereumAddress.js
  src/index.js
  src/lib/isEthereumAddress.js
  test/validators.js
  validator.js
  validator.min.js
Labels: mc-to-land, ready-to-land

#1081 Clean up PR 1021
  lib/toBoolean.js
  src/lib/toBoolean.js
  test/sanitizers.js
  validator.js
  validator.min.js
Labels: mc-to-land, ready-to-land

#1159 Added feature isHSL
  README.md
  src/index.js
  src/lib/isHSL.js
  test/validators.js
Labels: needs-more-review
