Repository validatorjs/validator.js, pull requests merged in 2020-12, with the labels that each got.

#1506 feature: Oman mobile phone validation added to isMobilePhone
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
  validator.js
  validator.min.js
Labels: 🎉 first-pr, 🧹 needs-update

#1536 feat(isVAT): add Italian regex
  README.md
  src/lib/isVAT.js
  test/validators.js
  validator.js
  validator.min.js
Labels: 🎉 first-pr

#1541 fix: update es-Co phone number
  src/lib/isMobilePhone.js
  test/validators.js
  validator.js
  validator.min.js
Labels: mc-to-land

#1505 feat Add support for Angola mobile phone numbers
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land, 🧹 needs-update

#1548 fix: add base58 and fix bech32 for is btc address
  src/lib/isBtcAddress.js
  test/validators.js
  validator.js
  validator.min.js
Labels: 🍿 discussion

#1554 fix(isMobilePhone): update de-CH locale (#1549)
  src/lib/isMobilePhone.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-more-review, 🎉 first-pr

#1495 feat(isLicensePlate): Introduction with locales for Germany, Liechtenstein, Portugal and Albania
  README.md
  index.js
  src/index.js
  src/lib/isLicensePlate.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-more-review, 🧹 needs-update

#1529 Fix el-GR isTaxID when checksum is 10
  src/lib/isTaxID.js
  test/validators.js
Labels: ready-to-land
