Repository validatorjs/validator.js, pull requests merged in 2020-11, with the labels that each got.

#1474 Make `isFQDN` more strict
  README.md
  src/lib/isFQDN.js
  test/validators.js
Labels: needs-more-review

#1286 isAlpha enhancement
  README.md
  src/lib/isAlpha.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-more-review

#1449 added email character blacklist
  README.md
  src/lib/isEmail.js
  test/validators.js
Labels: needs-more-review

#1454 Faster, more readable, less nested and more consistent function
  src/lib/util/assertString.js
Labels: needs-more-review

#1469 fix(isFQDN): allow all-underscore labels with allow_underscores (#1253)
  src/lib/isFQDN.js
  test/validators.js
Labels: mc-to-land

#1348 add isStrongPassword method
  README.md
  src/index.js
  src/lib/isStrongPassword.js
  test/sanitizers.js
  test/validators.js
Labels: needs-more-review, ✅ LGTM

#1486 feat(isISO8601): Add new option to isISO8601 that checks if date and time are strictly separated by a `T`
  README.md
  src/lib/isISO8601.js
  test/validators.js
  validator.js
  validator.min.js
Labels: needs-more-review, ✅ LGTM

#1446 feat(isTaxID): Add EU-UK TIN validation
  README.md
  src/lib/isTaxID.js
  src/lib/util/algorithms.js
  test/validators.js
Labels: needs-more-review

#1463 Implemented VAT validation support for english (en-GB) locale
  README.md
  src/index.js
  src/lib/isVAT.js
  test/validators.js
Labels: 🧹 needs-update
