Repository validatorjs/validator.js, pull requests merged in 2020-05, with the labels that each got.

#1293 Supported IBAN for Iran
  src/lib/isIBAN.js
  test/validators.js
Labels: 🧹 needs-update

#1315 feat: added zimbabwe mobile number validation
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land

#1317 Added postal code for nepal
  README.md
  es/lib/isPostalCode.js
  lib/isPostalCode.js
  src/lib/isPostalCode.js
  test/validators.js
Labels: 🧹 needs-update

#1316 Modified isJWT to use urlsafe base64 (also added)
  es/lib/isBase64.js
  es/lib/isJWT.js
  lib/isBase64.js
  lib/isJWT.js
  src/lib/isBase64.js
  src/lib/isJWT.js
  test/validators.js
Labels: needs-more-review

#1311 update nl_NL mobile phone to be correct (including test && src/lib && lib )
  lib/isMobilePhone.js
  src/lib/isMobilePhone.js
  test/validators.js
Labels: 🧹 needs-update

#1328 Fix #1327 : Adding option to allow primitives without BC break
  README.md
  src/lib/isJSON.js
  test/validators.js
  validator.js
  validator.min.js
Labels: 🧹 needs-update

#1330 Fix #1329 adding locale option for the isNumeric validator
  README.md
  src/lib/isNumeric.js
  test/validators.js
Labels: needs-more-review
