Repository validatorjs/validator.js, pull requests merged in 2021-10, with the labels that each got.

#1747 refactor: run scripts in parallel for build and clean
  package.json
Labels: ready-to-land, maintenance, 🎉 first-pr

#1641 feat(isEmail): add `host_blacklist` option
  README.md
  src/lib/isEmail.js
  test/validators.js
Labels: ready-to-land

#1745 feat(isIdentityCard): Add PL locale
  README.md
  src/lib/isIdentityCard.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1746 bugfix(isMobilePhone.js): Updating regex of Belgium and the valid and invalid phone numbers in validators.js
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1748 feat(isUrl): higher priority to whitelist
  src/lib/isURL.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1647 feat(isFQDN): add `allow_wildcard` option
  README.md
  src/lib/isFQDN.js
  test/validators.js
Labels: ready-to-land, 🍿 discussion, 🕑 to-be-reviewed, 🎉 first-pr

#1682 fix: use a loose and future-oriented way to verify Chinese mobile phone numbers
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1751 fix(isURL): allow URLs with column and no port
  src/lib/isURL.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1765 feat: (isMobilePhone) add Cuba validation
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1777 fix(isUUID): handle of null version value
  src/lib/isUUID.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1778 feat(isMobilePhone) Fix Mobile Phone Regex Pakistan(PK)
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1785 feat: (isMobilePhone) Enhancement to phone number validation regex in Sri Lanka (si-LK)
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, hacktoberfest-accepted

#1786 feat(isIdentityCard): Add isIdentityCard 'LK' (Sri Lanka) locale
  README.md
  src/lib/isIdentityCard.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1788 feat(isPostalCode): Add `LK` (Sri Lanka) locale
  README.md
  src/lib/isPostalCode.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1790 feat(isLicensePlate): fi-FI locale support
  README.md
  src/lib/isLicensePlate.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1799 check more special characters when validating a FQDN
  src/lib/isFQDN.js
  test/validators.js
Labels: ready-to-land, hacktoberfest-accepted

#1809 Updated Poland Country Code
  README.md
  src/lib/isPassportNumber.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1826 fix(isMobilePhone) - Update Hungarian mobile number validation
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1769 Added validation for Bermuda on isMobilePhone
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, mc-to-land, hacktoberfest-accepted

#1810 fix: Russian passport number regex
  src/lib/isPassportNumber.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1825 isVAT: added dutch VAT check
  README.md
  src/lib/isVAT.js
  test/validators.js
Labels: 🎉 first-pr

#1772 feat: (isMobilePhone) Add mobile phone validation for Cameroon (fr-CM)
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, mc-to-land, hacktoberfest-accepted

#1836 feat(contains): Added possibility to check that string contains seed multiple times
  README.md
  src/lib/contains.js
  test/validators.js
Labels: ready-to-land, needs-more-review

#1848 feat(isUUID) - Add support for validation of version v1 and v2
  README.md
  src/lib/isUUID.js
  test/validators.js
Labels: needs-more-review

#1846 feat(isMobilePhone): Add mobile phone validation locale for Tajikistan (tg-TJ)
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, hacktoberfest-accepted

#1770 feat(isMobilePhone): add Bhutan dz-BT locale
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, mc-to-land, hacktoberfest-accepted
