Repository validatorjs/validator.js, pull requests merged in 2021-04, with the labels that each got.

#1573 fix: update isMobilePhone validation for en-SG
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1594 Add support for IP version 4 or 6 for isIPRange function
  README.md
  src/lib/isIPRange.js
  test/validators.js
Labels: ready-to-land

#1595 feat: IR passport and identityCard, respect .gitignore files
  README.md
  src/lib/isIdentityCard.js
  src/lib/isPassportNumber.js
  test/validators.js
Labels: ready-to-land

#1625 Fix A-z ranges
  src/lib/isBIC.js
  src/lib/isISO31661Alpha2.js
  src/lib/isLocale.js
  src/lib/isPostalCode.js
Labels: ready-to-land, 🎉 first-pr

#1628 feat(isPostalCode): Add KR (Korea) postalCode validator and test.
  README.md
  src/lib/isPostalCode.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1632 [Fix] `isIP` validator patterns for IPv4 and IPv6 RegExp formats
  src/lib/isIP.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1633 isISIN optimization
  src/lib/isISIN.js
  test/validators.js
Labels: ready-to-land

#1635 fix(isMobilePhone): handle new networks codes in ghana
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1638 feat(isMobilePhone) new regex for Latvia lv-LV
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1640 typo: update README.md
  README.md
Labels: ready-to-land

#1642 China mobile phone number segment supplement
  src/lib/isMobilePhone.js
Labels: ready-to-land, 🎉 first-pr

#1644 isURL(): Allow URLs to have only a username in the userinfo subcomponent
  README.md
  src/lib/isURL.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1604 feat(isPassportNumber, isIBAN, isMobilePhone): updated to validate Mozambique passport, Mobile and IBAN number;
  README.md
  src/lib/isIBAN.js
  src/lib/isMobilePhone.js
  src/lib/isPassportNumber.js
  test/validators.js
Labels: mc-to-land, 🎉 first-pr

#1558 Fix: add Sierra Leone phone and fix Sri Lanka phone
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land

#1648 Add typeof utility
  src/lib/util/typeOf.js
  test/util.js
Labels: needs-more-review

#1654 feat(isRFC3339): Disallow prepended and appended strings to RFC 3339 date-time
  src/lib/isRFC3339.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr
