Repository validatorjs/validator.js, pull requests merged in 2021-07, with the labels that each got.

#1565 Add Czech license plates
  README.md
  src/lib/isLicensePlate.js
  test/validators.js
Labels: 🎉 first-pr, 🕑 to-be-reviewed

#1679 feat(isMobilePhone): change the german prefix from '+490' to '+49' or '0'
  src/lib/isMobilePhone.js
  test/validators.js
Labels: 🎉 first-pr

#1697 fix: npm installation error
  build-browser.js
  package.json
Labels: 🧹 needs-update

#1657 feat(isIdentityCard): add TH (Thai)
  README.md
  src/lib/isIdentityCard.js
  test/validators.js
Labels: 🎉 first-pr
