Repository validatorjs/validator.js, pull requests merged in 2021-03, with the labels that each got.

#1603 fix(isSlug & rtrim): regex no longer exposed to ReDOS attacks
  src/lib/isSlug.js
  src/lib/rtrim.js
Labels: needs-more-review

#1602 test: add `isSlug` test cases
  test/validators.js
Labels: needs-more-review

#1620 rephrase sentence for grammatical correctness
  README.md
Labels: ready-to-land, 🎉 first-pr

#1624 chore: improving code coverage to 100% branches
  src/lib/isLicensePlate.js
  src/lib/isStrongPassword.js
Labels: ready-to-land, 🎉 first-pr

#1623 Prevent isMobilePhone from allowing landline numbers in es-CO
  src/lib/isMobilePhone.js
  test/validators.js
Labels: needs-more-review

#1613 feat(pt-BR): tax id, passport and license plates
  README.md
  src/lib/isPassportNumber.js
  src/lib/isTaxID.js
  test/validators.js
Labels: needs-more-review, 🎉 first-pr

#1588 feat(isLicensePlate): adding license plate validators for 'mercosur' and 'pt-BR' locales
  README.md
  src/lib/isLicensePlate.js
  test/validators.js
Labels: needs-more-review, 🍿 discussion

#1574 Added Malaysian Passport validation
  README.md
  src/lib/isPassportNumber.js
  test/validators.js
Labels: mc-to-land, needs-more-review
