Repository validatorjs/validator.js, pull requests merged in 2021-09, with the labels that each got.

#1724 perf(isISO31661Alpha2): use a Set along with .has instead of includes
  src/lib/isBIC.js
  src/lib/isISO31661Alpha2.js
Labels: ready-to-land, 🎉 first-pr

#1730 fix(isMagnetURI): update validation regex
  src/lib/isMagnetURI.js
  test/validators.js
Labels: needs-more-review

#1706 feat(isISO4217): add currency code validator (#1703)
  README.md
  src/index.js
  src/lib/isISO4217.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1708 perf(isISO31661Alpha3): use a Set along with .has instead of includes
  src/lib/isISO31661Alpha3.js
Labels: ready-to-land

#1711 fix(validators): fix isdate format validation
  src/lib/isDate.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1714 feat(isPassportNumber): fix regex for CN
  src/lib/isPassportNumber.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1715 feat(isCreditCard): Fixed regex for Union Pay Credit cards with 81 range
  src/lib/isCreditCard.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1716 feat(isAlpha, isAlphanumeric): Adds Hindi (hi-IN) language support addition to isAlpha & isAlphanumeric
  README.md
  src/lib/alpha.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1718 fix(isEmail): replace all dots in gmail length validation
  src/lib/isEmail.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1721 feat(isURL): add `allow_fragments` and `allow_query_components`
  README.md
  src/lib/isURL.js
  test/validators.js
Labels: ready-to-land, enhancement, 🎉 first-pr

#1734 feat(isMobilePhone): Add validation for Venezuela phone numbers (#1720)
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land
