Repository validatorjs/validator.js, pull requests merged in 2022-06, with the labels that each got.

#1993 feat(isMobilePhone): Added regex for Mongolia mn-MN
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: 🎉 first-pr

#1951 fix: Modify pattern of pt-Br regex
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1956 fix: update bosnian, BA postal code
  README.md
  src/lib/isPostalCode.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1975 fix(matches): prevent regex state from breaking following validations
  src/lib/matches.js
Labels: ready-to-land

#1992 feat(isMagnetURI): support Bittorrent v2
  src/lib/isMagnetURI.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr

#1957 Fixed missing SK locale for isPostalCode
  README.md
Labels: ready-to-land, 🎉 first-pr
