Repository validatorjs/validator.js, pull requests merged in 2022-07, with the labels that each got.

#1985 feat(isMobilePhone): Added regex for Aruba nl-AW
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, mc-to-land

#1996 feat(isAlpha, isAlphanumeric): Adds Sinhala (si-LK) language support to isAlpha & isAlphanumeric
  README.md
  src/lib/alpha.js
  test/validators.js
Labels: 🕑 to-be-reviewed, 🎉 first-pr

#1922 feat(isMobilePhone): add Iran locale, ir-IR
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: 🎉 first-pr, mc-to-land

#1925 Added isMobilePhone valid regex for 3 countries
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land

#1940 feat(isMobilePhone): Added regex for Bahamas - en-BS
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land

#1909 feat (isMobilePhone): add Nicaragua validator
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land

#1897 feat: (isMobilePhone) add Cyprus validation
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: mc-to-land

#1678 feat(isAlpha, isAlphanumeric): Added support for Bengali language
  .gitignore
  README.md
  src/lib/alpha.js
  test/validators.js
Labels: 🧹 needs-update, needs-more-review, mc-to-land

#1989 Update isVAT.js
  README.md
  src/lib/isVAT.js
  test/validators.js
Labels: 🧹 needs-update, needs-more-review, 🎉 first-pr
