Repository validatorjs/validator.js, pull requests merged in 2023-06, with the labels that each got.

#2226 feat(isAlpha, isAlphanumeric): add kazakh locale, kk-KZ
  README.md
  src/lib/alpha.js
  test/validators.test.js
Labels: ✅ LGTM

#2117 refactor(isCreditCard): create allCards dynamically and get rid of hard-to-maintain hardcoded version
  src/lib/isCreditCard.js
Labels: enhancement

#2025 feat(isIBAN): add Morocco (MA) IBAN format
  src/lib/isIBAN.js
  test/validators.test.js
Labels: 🎉 first-pr
