Repository validatorjs/validator.js, pull requests merged in 2023-02, with the labels that each got.

#2046 fix(isBIC): add `XK` to accepted BIC country codes
  src/lib/isBIC.js
  test/validators.test.js
Labels: ready-to-land, 🎉 first-pr, ✅ LGTM

#2144 Added isContainerID validator
  README.md
  src/index.js
  src/lib/isISO6346.js
  test/validators.test.js
Labels: 🎉 first-pr, mc-to-land, ✅ LGTM

#2175 feat(isMobilePhone): Add regex for Somalia so-SO
  README.md
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ready-to-land, 🎉 first-pr, mc-to-land, ✅ LGTM

#2176 feat(isMobilePhone): Add Central African Republic Locale And Prefix(CF)
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM
