Repository validatorjs/validator.js, pull requests merged in 2023-01, with the labels that each got.

#2142 Added support for zh-HK in isIdentityCard
  README.md
  src/lib/isIdentityCard.js
  test/validators.js
Labels: 🎉 first-pr

#2084 feat(isMobilePhone): Add South Sudan Locale And Prefix(SS)
  README.md
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, ✅ LGTM

#2148 Validator does not recognise £ as symbol
  src/lib/isStrongPassword.js
  test/validators.js
Labels: 🎉 first-pr, ✅ LGTM

#2138 feat(isMobilePhone): added Virgin Mobile provider to (ar-KW).
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, 🎉 first-pr, ✅ LGTM

#2137 test(validators): remove duplicated test block from isMobilePhone
  test/validators.js
Labels: ready-to-land, ✅ LGTM

#2136 fix(isPostalCode): fix overly permissive IR regexp
  src/lib/isPostalCode.js
  test/validators.js
Labels: ready-to-land, ✅ LGTM

#2132 refactor(isBtcAddress): get rid of unnecessary if statement and comment
  src/lib/isBtcAddress.js
Labels: ready-to-land, ✅ LGTM

#2129 fix(isMobilePhone): re-add es-HN fix from #1983
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, ✅ LGTM

#2122 fix(isDataURI): Fix MIME Types with underscores not getting matched
  src/lib/isDataURI.js
  test/validators.js
Labels: ready-to-land, ✅ LGTM

#2112 fix(isMobilePhone): Fix el-GR validation - Add missing ranges + correctly exclude certain ranges
  src/lib/isMobilePhone.js
  test/validators.js
Labels: ready-to-land, ✅ LGTM

#1479 added isTime validator
  README.md
  src/index.js
  src/lib/isTime.js
  test/validators.js
Labels: needs-more-review, 🎉 first-pr, ✅ LGTM, 🔥 new validator, v-next

#2134 fix(isPostalCode): Fix overly permissive BY regexp
  src/lib/isPostalCode.js
  test/validators.js
Labels: ready-to-land, ✅ LGTM

#2091 refactor: change test files to prepare for #1874
  package.json
  test/clientSide.test.js
  test/exports.test.js
  test/sanitizers.test.js
  test/testFunctions.js
  test/util.test.js
  test/validators.test.js
Labels: ✅ LGTM

#2118 docs(CHANGELOG): remove duplicated "New Features" section
  CHANGELOG.md
Labels: ✅ LGTM

#2109 fix(isMobilePhone): Fix wrong dv-MV mobile phone matching (issue #2101)
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: mc-to-land, ✅ LGTM

#2107 docs: Improve consistency and fix errors in README.md
  README.md
Labels: mc-to-land, ✅ LGTM

#2085 fix(isLicensePlate): remove duplicate char from character class
  src/lib/isLicensePlate.js
Labels: 🎉 first-pr

#2120 fix(isMimeType): Fix MIME Types with underscores not getting matched
  src/lib/isMimeType.js
  test/validators.test.js
Labels: ✅ LGTM

#2156 fix(isMobilePhone): fix 'ro-RO' matching invalid numbers
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM

#2155 fix(isMobilePhone): fix 'ms-MY' matching invalid numbers
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM

#2116 fix(isMobilePhone): Fix en-BM matching invalid numbers due to missing end-of-string anchor
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM

#2114 fix(isRgbColor): Fix validation of rgb(a)ColorPercentage strings
  src/lib/isRgbColor.js
  test/validators.test.js
Labels: ✅ LGTM

#2075 feat(isAfter): allow usage of options object
  README.md
  src/lib/isAfter.js
  src/lib/toDate.js
  test/validators.test.js
  test/validators/isAfter.test.js
Labels: ✅ LGTM

#2157 feat(isISBN): allow usage of options object
  README.md
  src/lib/isISBN.js
  test/validators.test.js
  test/validators/isISBN.test.js
Labels: needs-more-review
