Repository validatorjs/validator.js, pull requests merged in 2024-04, with the labels that each got.

#2371 fixed typo in README.md
  README.md
Labels: ready-to-land, 🎉 first-pr

#2345 feat(isUUID): support uuid v7
  src/lib/isUUID.js
  test/validators.test.js
Labels: ready-to-land

#2284 fix(isPassportNumber): fix regex Azerbaijan
  src/lib/isPassportNumber.js
  test/validators.test.js
Labels: 🎉 first-pr, ✅ LGTM

#2285 feat(isAlpha, isAlphanumeric): add Esperanto (eo) locale
  README.md
  src/lib/alpha.js
  test/validators.test.js
Labels: ✅ LGTM

#2271 fix(isPostalCode): Improve Dutch postal code regex
  src/lib/isPostalCode.js
  test/validators.test.js
Labels: ✅ LGTM

#2211 Fix(isPort): Invalid leading zeros (#2208)
  src/lib/isInt.js
  src/lib/isPort.js
  test/validators.test.js
Labels: ✅ LGTM

#2207 feat(isLicensePlate): Support for Pakistani vehicles
  README.md
  src/lib/isLicensePlate.js
  test/validators.test.js
Labels: 🧹 needs-update, ✅ LGTM

#2143 Added isAbaRouting validator
  README.md
  src/index.js
  src/lib/isAbaRouting.js
  test/validators.test.js
Labels: 🍿 discussion, ✅ LGTM

#2140 isMobilePhone - fixed validation for am-AM
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: 🎉 first-pr, ✅ LGTM

#2386 Moved repository contributing guidelines to CONTRIBUTING.md and updated README.md
  CONTRIBUTING.md
  README.md
Labels: 🎉 first-pr
