Repository validatorjs/validator.js, pull requests merged in 2024-06, with the labels that each got.

#1971 feat(isMobilePhone): en-GB enhance
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM

#2406 feat(isBtcAddress): :sparkles: Support all address formats and testnets
  src/lib/isBtcAddress.js
  test/validators.test.js
Labels: ✅ LGTM

#2395 add guatemala phone number
  README.md
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM

#2394 fix(docs) Add Esperanto support to README.md
  README.md
Labels: ready-to-land, ✅ LGTM

#2359 fix(isMobilePhone): update phone regex for Ukraine uk-UA
  src/lib/isMobilePhone.js
  test/validators.test.js
Labels: ✅ LGTM

#2402 doc: Update README.md for installation with other package managers
  README.md
Labels: ✅ LGTM

#1732 add license badges to the readme file
  README.md
Labels: 🎉 first-pr, ✅ LGTM

#2291 Added support for PK(Pakistan) in isIdentityCard
  README.md
  src/lib/isIdentityCard.js
  test/validators.test.js
Labels: ✅ LGTM

#2416 fix(isInt, isFloat): Handle undefined and null values
  src/lib/isFloat.js
  src/lib/isInt.js
  src/lib/util/nullUndefinedCheck.js
  test/validators.test.js
Labels: ✅ LGTM

#2415 feat(isPostalCode): add validation for Colombian postal code
  README.md
  src/lib/isPostalCode.js
  test/validators.test.js
Labels: ✅ LGTM

#2404 Fix for ticket #2403 "get list of supported countries for passports"
  README.md
  src/index.js
  src/lib/isPassportNumber.js
  test/exports.test.js
Labels: ✅ LGTM

#2323 docs: fix typos
  README.md
Labels: ✅ LGTM

#2029 feat(isRgbColor): add `allowSpaces` option to allow/disallow spaces between color values
  README.md
  src/lib/isRgbColor.js
  test/validators.test.js
Labels: enhancement, 🎉 first-pr, ✅ LGTM

#2294 feat(ulid): ULID validation
  README.md
  src/index.js
  src/lib/isULID.js
  test/validators.test.js
Labels: ✅ LGTM
